name: deploy-saleapp-on-AWS-EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Habilita a VM do actions a acessar os objetos do repositório
      - name: Deploy na instancia EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }} # Chave SSH
          USER: ubuntu # Usuário SSH na instância EC2
          HOST: 44.215.252.109
        run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 700 deploy_key.pem
          ssh -i deploy_key.pem $USER@$HOST
          echo "user $USER connected to $HOST by ssh"
      
          
      
      
