name: deploy-saleapp-on-AWS-EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Habilita a VM do actions a acessar os objetos do repositório
      - name: Deploy na instancia EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }} # Chave SSH
          USER: ec2-user # Usuário SSH na instância EC2
          HOST: ec2-34-232-74-209.compute-1.amazonaws.com
        run: |
          echo "$PRIVATE_KEY" > deploy_key
          chmod 400 deploy_key
          ssh -i deploy_key $USER@$HOST "cd /apps/saleapp/backend/app && git pull origin main && stop_services.sh && remove.sh && build.sh && up_services.sh"
      
          
      
      
