name: deploy-saleapp-on-AWS-EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy na instancia EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }} # Chave SSH
          USER: ubuntu # Usuário SSH na instância EC2
          HOST: 44.215.252.109
        run: |
          ssh-keygen -R 44.215.252.109
          echo "$PRIVATE_KEY" > ApplicationServerKeyPair.pem
          chmod 700 ApplicationServerKeyPair.pem
          ssh -i ApplicationServerKeyPair.pem $USER@$HOST
          echo "user $USER connected to $HOST by ssh"
      
          
      
      
